### ISSUE TITLE
Merging efforts

### ISSUE THREAD

**Issue by Urigo** [Saeris/graphql-scalars#23]
Hi @Saeris !

This library looks great!

We've just took over maintenance of [graphql-scalars](https://github.com/urigo/graphql-scalars) from OK-Grow: https://medium.com/the-guild/the-guild-is-taking-over-maintenance-of-merge-graphql-schemas-so-lets-talk-about-graphql-schema-46246557a225

@ardatan has already migrated the codebase to Typescript.

I've seen your library which was a fork of the original one.

What do you think about collaborating together and merging our efforts?

Let me know your thoughts!

**Comment by Saeris** [comment]
Hey, thanks for reaching out!

I haven't had time to maintain my fork lately since I picked up full-time work. You're welcome to use code from this project in your own, but at the moment I can't commit to collaborating.

**Comment by Urigo** [comment]
@Saeris thank you for your comment!

What do you think are the main additions or changes you've made on this fork that you recommend me to look at?

also, will it be beneficial for users of this library to know it is now less maintained and maybe point them to our library instead?
